name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
       with:
         persist-credentials: false
     - name: Setup Node.js
       uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
       with:
         node-version: 22
     - run: npm ci --ignore-scripts
     - run: npx bsfmt --check --bsfmt-path "bsfmt.json"
     - name: Check the npm package installs with ropm
       run: npm run test:package
